# Generated by Django 5.2 on 2025-04-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('quantity', models.IntegerField(default=450, verbose_name='quantity in ml')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DonationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('district', models.CharField(max_length=100, verbose_name='district')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='working hours')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'donation center',
                'verbose_name_plural': 'donation centers',
                'ordering': ['name', 'city'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='patient name')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3, verbose_name='blood type')),
                ('hospital', models.CharField(max_length=100, verbose_name='hospital')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='district')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('units_needed', models.IntegerField(default=1, verbose_name='units needed')),
                ('units_received', models.IntegerField(default=0, verbose_name='units received')),
                ('urgency_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, verbose_name='urgency level')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='additional information')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'emergency request',
                'verbose_name_plural': 'emergency requests',
                'ordering': ['-urgency_level', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('response_time', models.DateTimeField(auto_now_add=True, verbose_name='response time')),
                ('donation_time', models.DateTimeField(blank=True, null=True, verbose_name='donation time')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'emergency response',
                'verbose_name_plural': 'emergency responses',
                'ordering': ['-response_time'],
            },
        ),
    ]
