# Generated by Django 5.2 on 2025-04-05 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='donor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donationcenter', verbose_name='donation center'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to=settings.AUTH_USER_MODEL, verbose_name='requester'),
        ),
        migrations.AddField(
            model_name='emergencyresponse',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_responses', to=settings.AUTH_USER_MODEL, verbose_name='donor'),
        ),
        migrations.AddField(
            model_name='emergencyresponse',
            name='emergency_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='donations.emergencyrequest', verbose_name='emergency request'),
        ),
    ]
